import type { Edge, Node } from "@xyflow/react";

/** Topologically sort a DAG (best-effort; cycles will just give partial order) */
function topo(nodes: Node[], edges: Edge[]): string[] {
  const indeg: Record<string, number> = {};
  const adj = new Map<string, string[]>();
  nodes.forEach(n => { indeg[n.id] = 0; adj.set(n.id, []); });
  edges.forEach(e => {
    indeg[e.target] = (indeg[e.target] ?? 0) + 1;
    adj.get(e.source)!.push(e.target);
  });
  const q = nodes.filter(n => indeg[n.id] === 0).map(n => n.id);
  const out: string[] = [];
  while (q.length) {
    const u = q.shift()!;
    out.push(u);
    (adj.get(u) ?? []).forEach(v => {
      indeg[v]--;
      if (indeg[v] === 0) q.push(v);
    });
  }
  return out.length ? out : nodes.map(n => n.id);
}

function indegreeMap(nodes: Node[], edges: Edge[]) {
  const indeg: Record<string, number> = {};
  nodes.forEach(n => (indeg[n.id] = 0));
  edges.forEach(e => (indeg[e.target] = (indeg[e.target] ?? 0) + 1));
  return indeg;
}

function outdegreeMap(nodes: Node[], edges: Edge[]) {
  const outdeg: Record<string, number> = {};
  nodes.forEach(n => (outdeg[n.id] = 0));
  edges.forEach(e => (outdeg[e.source] = (outdeg[e.source] ?? 0) + 1));
  return outdeg;
}

const header = `# Generated by LangBlock (LangGraph export)
# Requirements:
#   pip install langgraph langchain langchain-openai
#   export OPENAI_API_KEY=...

from typing import TypedDict, List, Dict, Any
from langgraph.graph import StateGraph, START, END
from langchain_core.messages import AIMessage, HumanMessage, BaseMessage
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(dotenv_path=str((Path(__file__).resolve().parent.parent / ".env")))

class State(TypedDict, total=False):
    # free-form graph state; extend as needed
    input: str
    messages: List[BaseMessage]
    result: str

# Shared LLM (customize model/temperature per node if you like)
# Per-node configs will override this default when present.
_default_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

`;

const footer = `
def build_graph():
    workflow = StateGraph(State)
    # --- register nodes ---
{REGISTER_NODES}
    # --- wire edges ---
{ADD_EDGES}
    # START/END glue
{START_EDGES}
{END_EDGES}
    return workflow.compile()

if __name__ == "__main__":
    graph = build_graph()
    # Minimal demo run
    initial = {"input": "Hello from LangBlock!", "messages": []}
    out = graph.invoke(initial)
    # Prefer explicit 'result', else last AI message content
    if "result" in out:
        print(out["result"])
    elif out.get("messages"):
        last = out["messages"][-1]
        print(getattr(last, "content", last))
    else:
        print(out)
`;

export function generatePython(nodes: Node[], edges: Edge[]): string {
  // Map node id -> kind/config
  const idTo = new Map<string, { kind: string; label: string; config: any }>();
  nodes.forEach(n => {
    const d: any = n.data || {};
    idTo.set(n.id, {
      kind: (d.kind || d.type || "").toLowerCase(),
      label: d.label || n.id,
      config: d.config || {}
    });
  });

  const lines: string[] = [header];

  // 1) Emit node functions
  const order = topo(nodes, edges);
  for (const nid of order) {
    const meta = idTo.get(nid)!;
    const kind = meta.kind;

    if (kind === "input") {
      lines.push(`
def node_${nid}(state: State) -> State:
    # Input node: ensure 'messages' list exists and pass through input
    msgs = list(state.get("messages") or [])
    # Optionally turn raw input into a HumanMessage for downstream use
    if state.get("input"):
        msgs.append(HumanMessage(content=str(state["input"])))
    return {"messages": msgs}
`);
      continue;
    }

    if (kind === "prompt") {
      const tpl = JSON.stringify(meta.config?.template ?? "Answer briefly: {input}");
      lines.push(`
def node_${nid}(state: State) -> State:
    # PromptTemplate -> append a HumanMessage rendered from state
    template = PromptTemplate.from_template(${tpl})
    text = template.format(**{"input": state.get("input","")})
    msgs = list(state.get("messages") or [])
    msgs.append(HumanMessage(content=text))
    return {"messages": msgs}
`);
      continue;
    }

    if (kind === "llm") {
      const model = JSON.stringify(meta.config?.model ?? "gpt-4o-mini");
      const temp  = Number(meta.config?.temperature ?? 0);
      lines.push(`
def node_${nid}(state: State) -> State:
    # LLM consumes accumulated messages and appends an AIMessage
    llm = ChatOpenAI(model=${model}, temperature=${temp})
    msgs = list(state.get("messages") or [])
    if not msgs and state.get("input"):
        msgs.append(HumanMessage(content=str(state["input"])))
    ai = llm.invoke(msgs)
    msgs.append(ai)
    return {"messages": msgs}
`);
      continue;
    }

    if (kind === "tool") {
      const name = JSON.stringify(meta.config?.name ?? "tool");
      const args = JSON.stringify(meta.config?.args ?? "{}");
      lines.push(`
def node_${nid}(state: State) -> State:
    # Stub tool node
    msgs = list(state.get("messages") or [])
    msgs.append(AIMessage(content=f"[${name}] called with ${args}"))
    return {"messages": msgs}
`);
      continue;
    }

    if (kind === "output") {
      lines.push(`
def node_${nid}(state: State) -> State:
    # Output node: finalize 'result' from last AI message (fallback to last message text)
    msgs = list(state.get("messages") or [])
    if msgs:
        last = msgs[-1]
        content = getattr(last, "content", str(last))
    else:
        content = str(state.get("input",""))
    return {"result": content, "messages": msgs}
`);
      continue;
    }

    // Fallback passthrough
    lines.push(`
def node_${nid}(state: State) -> State:
    return {}
`);
  }

  // 2) Build wiring
  const register: string[] = [];
  order.forEach(nid => {
    register.push(`    workflow.add_node("${nid}", node_${nid})`);
  });

  const addEdges: string[] = [];
  edges.forEach(e => {
    addEdges.push(`    workflow.add_edge("${e.source}", "${e.target}")`);
  });

  // START: nodes with indegree 0
  const indeg = indegreeMap(nodes, edges);
  const startNodes = Object.keys(indeg).filter(id => indeg[id] === 0);
  const startGlue = startNodes.length
    ? startNodes.map(id => `    workflow.add_edge(START, "${id}")`).join("\n")
    : "    # (no zero-indegree nodes found)";

  // END: nodes with outdegree 0
  const outdeg = outdegreeMap(nodes, edges);
  const endNodes = Object.keys(outdeg).filter(id => outdeg[id] === 0);
  const endGlue = endNodes.length
    ? endNodes.map(id => `    workflow.add_edge("${id}", END)`).join("\n")
    : "    # (no zero-outdegree nodes found)";

  // 3) Attach footer with placeholders filled
  const body = footer
    .replace("{REGISTER_NODES}", register.join("\n"))
    .replace("{ADD_EDGES}", addEdges.join("\n") || "    # (no edges)")
    .replace("{START_EDGES}", startGlue)
    .replace("{END_EDGES}", endGlue);

  lines.push(body);
  return lines.join("\n");
}